# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 717ed32807db81d72f6d11f614fceb5b41a1850e6345118a9bbb5638776a559c7540087676d4b06a14ac774eedfe6047c0388318b167fe49f41347103ec461a9

test:
  secret_key_base: c02259bf70386eb118ffd9373b455a60aa96537dac8cd44e02447665ff22487aa489fc84d8559015b66c12aef4e0e80cc2ada24bae1d974d5db8c2a8b5695dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
